config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: 'stories#index'

  resources :stories, only: [:index, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/story.rb
class Story < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
   def index
    @stories = Story.all
  end

  def show
    @story = Story.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Plume Challenge</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <main class="container mx-auto px-5 flex bg-grey-100">
      <%= turbo_frame_tag "modal" %>
      <%= yield %>
    </main>
  </body>
</html>

app/views/stories/index.html.erb
<div>

<% @stories.uniq{|s| s.universe_name }.each do |story| %>
  <div class="">
    <h1 class="font-bold text-xl mb-4 mt-5">Dans l'univers "<%= story.universe_name %>"
    <span class="bg-yellow-500"> <%= "Recommandé" if story.universe_name == 'L\'île mystérieuse'  %> </span>
    </h1>
    <div class="bg-white rounded shadow-md grid lg:grid-cols-5 gap-8 mb-4">
      <% @stories.where(universe_name: story.universe_name).each do |s| %>
        <%= link_to story_path(s), data: { turbo_frame: 'modal' } do %>
        <div class="overflow-hidden relative">
          <div class="">
            <%= cl_image_tag(s.key, :width=>270, :height=>253, :crop=>"scale") %>
            <img src="s.key" alt="" class="w-full sm:h-70 ">
          </div>
          <div class="text-center m-4 ">
            <h1 class="font-bold text-xl"><%= s.title %></h1>
            <p class="text-neutral-300 text-center">
              <%= s.description.first(50) %>
            </p>
          </div>
          <div class="bg-grey-100 text-secondary-200 rounded-full p-2 absolute right-1 top-24 mt-5 ml-2">
            <span> <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTTx19bOhMDVwBVaX6CfPb6r-hUXWBJEvRetw&usqp=CAU" alt="" class="h-12 xl:h-20 rounded-full mt-5"></span>
          </div>
        </div>
        <% end %>
      <% end %>
    </div>
  </div>
<% end %>
</div>

app/views/stories/show.html.erb
<%= turbo_frame_tag "modal" do %>
        <%= tag.div data: { controller: "turbo-modal" }, style: "padding: 30px;" do %>
<div class="bg-black bg-opacity-50 fixed inset-0 z-10 flex justify-center items-center">

  <div class="max-w-sm mx-auto rounded overflow-hidden shadow-lg bg-white relative ">
    <div class="relative"> <%= cl_image_tag(@story.key, :width=>700, :height=>500, :crop=>"scale") %>
    <%= button_tag "X", data: { action: "turbo-modal#hideModal" }, type: "button", class: "rounded-full py-3 px-5 bg-white text-red-600 absolute top-5 right-3" %></div>

    <div class="px-6 py-4 bg-white">
      <div class="font-bold mb-2 text-center  ">
        <span class="text-left ">
          <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1" d="M15.536 8.464a5 5 0 010 7.072m2.828-9.9a9 9 0 010 12.728M5.586 15H4a1 1 0 01-1-1v-4a1 1 0 011-1h1.586l4.707-4.707C10.923 3.663 12 4.109 12 5v14c0 .891-1.077 1.337-1.707.707L5.586 15z" />
          </svg>
    <button class="rounded-full py-3 px-5 bg-white text-red-600 ml-2 absolute top-40 left-3">
      <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 19l-7-7 7-7" />
      </svg>
    </button>
        </span>
      <span>  <%= @story.title %>
    <button class="rounded-full py-3 px-5 bg-white text-red-600 ml-2 absolute top-40 right-3 ml-5">
      <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7" />
      </svg>
    </button> </span>
      </div>
    <p class="text-center m-2">
      <%= @story.description.first(124) %>
      <br>
      <button class="bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded mt-2">
        Commencer cette histoire
      </button>
    </p>
    </div>
  </div>
</div>
  <% end %>
<% end %>